### ISSUE TITLE
'make build' failed after release 1.1.0

### ISSUE THREAD

**Issue by kormotodor** [justwatchcom/elasticsearch_exporter#274]
I faced with this issue after 1.1.0 release.
CI was working perfectly on 1.1.0rc1.

make build:
```
go: finding golang.org/x/sync latest
go: finding github.com/alecthomas/units latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding github.com/alecthomas/template latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/crypto latest
go: finding github.com/prometheus/client_model latest
go: finding gopkg.in/check.v1 latest
go: finding golang.org/x/time latest
go: finding golang.org/x/lint latest
go: finding github.com/google/pprof latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding github.com/kr/logfmt latest
go: finding google.golang.org/genproto latest
go: finding github.com/modern-go/concurrent latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/exp latest
go: finding golang.org/x/mobile latest
go: finding github.com/golang/glog latest
go: finding golang.org/x/xerrors latest
go: finding github.com/BurntSushi/xgb latest
go: finding golang.org/x/image latest
>> building binaries
 >   elasticsearch_exporter
# github.com/justwatchcom/elasticsearch_exporter
./main.go:163:27: undefined: prometheus.Handler
!! command failed: build -o /var/lib/jenkins/jobs/prometheus/jobs/elasticsearch-exporter-deb/workspace/src/github.com/justwatchcom/elasticsearch_exporter/elasticsearch_exporter -ldflags -s -X github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/common/version.Version=1.1.0 -X github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/common/version.Revision=non-git -X github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/common/version.Branch=non-git -X github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/common/version.BuildUser=root@devops -X github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/common/version.BuildDate=20190808-12:16:17  -extldflags '-static' -a -tags netgo github.com/justwatchcom/elasticsearch_exporter: exit status 2
Makefile:44: recipe for target 'build' failed
make: *** [build] Error 1
```
My 'go env' output:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12.2"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/var/lib/jenkins/jobs/prometheus/jobs/elasticsearch-exporter-deb/workspace/src/github.com/justwatchcom/elasticsearch_exporter/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build287362171=/tmp/go-build -gno-record-gcc-switches"
```
And 'go version':
```
go version go1.12.2 linux/amd64
```

**Comment by kormotodor** [comment]
# make vet:
```
>> vetting code
# github.com/justwatchcom/elasticsearch_exporter [github.com/justwatchcom/elasticsearch_exporter.test]
./main.go:163:27: undefined: prometheus.Handler
Makefile:40: recipe for target 'vet' failed
make: *** [vet] Error 2
```

**Comment by zwopir** [comment]
Hi @kormotodor,

I can't reproduce your issue but I assume it's a go mod issue. In my `go env` output `GOMOD` is empty and the build and vet succeeds

**Comment by kormotodor** [comment]
@zwopir, yeah thank you a lot. Setting `GOMOD` to  `""` and building with `go build` realy fixes that issue.
